### ISSUE TITLE
Streaming not supported.

### ISSUE THREAD

**Issue by vladaman** [jinvillaz-zz/gulp-scp3#1]
I am getting - is there any way to fix this?

```
[17:18:15] Starting 'deploy'...
Error: Streaming not supported.

at node_modules/gulp-scp3/lib/gulp-scp.js:44:29)
```

**Comment by jinvillaz-zz** [comment]
could you give me the scenery? The objective for this library is upload files remotely like scp command in linux, in this case we using as a gulp task.

**Comment by vladaman** [comment]
Yes, and Thanks for your help! My current gulp task (code simplified):

```javascript
var scp = require('gulp-scp3');

gulp.task( 'deploy', function () {
 var globs = [ '../../login/**'];
 return gulp.src(globs, { base: '../', buffer: false })
    .pipe(scp({
        host: 'myhostname',
        username: 'sftp-user',
        password: ftpPassword,
        dest: '/site.com/'
    }));
});
```

I get following error when I run `gulp deploy`

```
[15:15:01] Using gulpfile ~/tmp/webapp/angularadminweb/main/master/gulpfile.js
[15:15:01] Starting 'deploy'...
[15:15:01] 'deploy' errored after 89 ms
[15:15:01] Error: Streaming not supported.
    at DestroyableTransform.through.obj [as _transform] (/home/vlad/tmp/webapp/angularadminweb/main/master/node_modules/gulp-scp3/lib/gulp-scp.js:44:29)
    at DestroyableTransform.Transform._read (/home/vlad/tmp/webapp/angularadminweb/main/master/node_modules/gulp-scp3/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write (/home/vlad/tmp/webapp/angularadminweb/main/master/node_modules/gulp-scp3/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/vlad/tmp/webapp/angularadminweb/main/master/node_modules/gulp-scp3/node_modules/readable-stream/lib/_stream_writable.js:405:139)
    at writeOrBuffer (/home/vlad/tmp/webapp/angularadminweb/main/master/node_modules/gulp-scp3/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at DestroyableTransform.Writable.write (/home/vlad/tmp/webapp/angularadminweb/main/master/node_modules/gulp-scp3/node_modules/readable-stream/lib/_stream_writable.js:303:11)
    at DestroyableTransform.ondata (/home/vlad/tmp/webapp/angularadminweb/main/master/node_modules/to-through/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
    at addChunk (/home/vlad/tmp/webapp/angularadminweb/main/master/node_modules/to-through/node_modules/readable-stream/lib/_stream_readable.js:291:12)
```
Versions:
```
gulp --version
CLI version: 2.2.0
Local version: 4.0.0
```

**Comment by jinvillaz-zz** [comment]
what version of node.js are you using? 
dest: '/site.com/'
I'm not sure if this works. You need to use the fullpath like scp command. "/home/user/test"
and you need the permission for writing for that path
